#!/usr/bin/env bash

set -e

RELEASE_NAME=example-docker-usage
DOCKER_PACKAGE_DIR=$(pwd)
NAME=${RELEASE_NAME}-$(basename $DOCKER_PACKAGE_DIR)

WORK_DIR=$(mktemp -d -t XXXXXX)

cp -a ${DOCKER_PACKAGE_DIR}/Dockerfile $WORK_DIR/

for blob in $(<${DOCKER_PACKAGE_DIR}/blobs)
do
  filename=$(basename ${blob})
  abs_blob_path=$(readlink ${DOCKER_PACKAGE_DIR}/../../blobs/${blob})
	cp -a ${abs_blob_path} $WORK_DIR/$filename
done

cd $WORK_DIR && docker build -t $NAME .

docker images | head -n 1
docker images | grep $NAME
