#!/usr/bin/env bash

set -e

DOCKER_PACKAGE_DIR=$(pwd)
NAME=$(basename $DOCKER_PACKAGE_DIR)

WORK_DIR=$(mktemp -d -t XXXXXX)

cp -a ${DOCKER_PACKAGE_DIR}/Dockerfile $WORK_DIR/

for blob in $(<${DOCKER_PACKAGE_DIR}/blobs)
do
  filename=$(basename ${blob})
  abs_blob_path=$(readlink ${DOCKER_PACKAGE_DIR}/../../blobs/${blob})
  echo $abs_blob_path
  echo $filename
	cp -a ${abs_blob_path} $WORK_DIR/$filename
done

cd $WORK_DIR && docker build -t $NAME .

docker images | head -n 2
