#!/usr/bin/env bash

set -e

DOCKER_PACKAGE_DIR=$(pwd)
NAME=$(basename $DOCKER_PACKAGE_DIR)

WORK_DIR=$(mktemp -d -t XXXXXX)

cp -a ${DOCKER_PACKAGE_DIR}/Dockerfile $WORK_DIR/

for blob in $(<${DOCKER_PACKAGE_DIR}/blobs)
do
	cp -a ${DOCKER_PACKAGE_DIR}/../../blobs/${blob} $WORK_DIR/
done

docker build -t $NAME $WORK_DIR

docker images | head -n 2
