#!/usr/bin/env bash

set -e

REGISTRY_CACHE=$(mktemp -d -t docker)

CONTAINER_ID=$(docker run -d -v ${REGISTRY_CACHE}:/registry -p 5000:5000 drnic/docker-registry)

REGISTRY_HOST=${DOCKER_HOST:-localhost}
REGISTRY_HOST_PORT=$(docker inspect -format='{{range $p, $conf := .NetworkSettings.Ports}}{{(index $conf 0).HostPort}}{{end}}' $CONTAINER_ID)

echo "$REGISTRY_HOST:$REGISTRY_HOST_PORT"

curl -v http://$REGISTRY_HOST:$REGISTRY_HOST_PORT/v1/_ping

docker stop $CONTAINER_ID