#!/usr/bin/env bash

set -e

REGISTRY_CACHE=$(mktemp -d -t docker)

echo "Starting registry..."
CONTAINER_ID=$(docker run -d -v ${REGISTRY_CACHE}:/registry -p 5000:5000 drnic/docker-registry)

REGISTRY_HOST=localhost
REGISTRY_HOST_PORT=$(docker inspect -format='{{range $p, $conf := .NetworkSettings.Ports}}{{(index $conf 0).HostPort}}{{end}}' $CONTAINER_ID)

sleep 2
found=$(curl -s --retry-delay 1 --retry 3 http://$REGISTRY_HOST:$REGISTRY_HOST_PORT/v1/_ping)
if [[ "${found}" != "true" ]]; then
	echo Registry did not come up at http://$REGISTRY_HOST:$REGISTRY_HOST_PORT
	docker stop $CONTAINER_ID
	exit 1
fi

echo "Stopping registry..."
docker stop $CONTAINER_ID